---
name: "yt-dlp"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "0.1.0.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "Automated YouTube video downloading and organization using yt-dlp"
description: >
  A Jellyfin plugin that integrates yt-dlp for automated downloading and
  organization of YouTube videos. Supports channels, playlists, custom
  organization rules, and full metadata preservation.
category: "General"
owner: "rdeusser"
artifacts:
- "Jellyfin.Plugin.YtDlp.dll"
changelog: >
  Initial release
